// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Provider from "./provider";
// import ConvexClientProvider from "./ConvexClientProvider";
// import { Toaster } from "sonner";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
        
//       >
//       <ConvexClientProvider>
//       <Provider>{children}
//       <Toaster/>
//       </Provider>
//       </ConvexClientProvider>
//       </body>
//     </html>
//   );
// }
import "./globals.css";
import Provider from "./provider";
import ConvexClientProvider from "./ConvexClientProvider";
import { Toaster } from "sonner";
import Header from "@/components/Custom/Header";
import { ActionProvider } from "@/app/context/ActionContext";
import AppSideBar from "@/components/Custom/AppSideBar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ConvexClientProvider>
          <Provider>
            <ActionProvider>
              <Header />
                  <div className="flex w-full min-h-screen">
                    <AppSideBar />
                    <main className="flex flex-col items-center justify-center min-h-screen flex-1">
                      {children}
                    </main>
                  </div>
              <Toaster />
            </ActionProvider>
          </Provider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}